const products = [
  {id:2,name:'Antes De Ti',src:'Images/AntesDeTi.jpg',price:'$30.000',},
  {id:3,name:'A Dos Metros De Ti',src:'Images/ADosMetros.jpg',price:'$15.000',},
  {id:4,name:'El Principito',src:'Images/ElPrincipito.jpg',price:'$9.000',},
  {id:5,name:'Don Quijote De La Mancha',src:'Images/DonQuijoteDeLaMancha.jpg',price:'$12.000',},
  {id:6,name:'Orgullo Y Prejuicio',src:'Images/OrgulloYPrejuicio.jpg',price:'$12.000',},
  {id:7,name:'100 Años De Soledad',src:'Images/CienAñosDeSoledad.jpg',price:'$12.000',},
  {id:8,name:'La Ladrona De Libros',src:'Images/LaLadronaDeLibros.jpg',price:'$12.000',},
  {id:9,name:'La Divina Comedia',src:'Images/LaDivinaComedia.jpg',price:'$12.000',},
  {id:10,name:'Cumbres Borrascosas',src:'Images/CumbresBorrascosas.jpg',price:'$12.000',},
  {id:11,name:'El Codigo Da Vinci',src:'Images/ElCodigoDaVinci.jpg',price:'$12.000',},
  {id:12,name:'Harry Potter Y La Piedra Filosofal',src:'Images/HarryPotterYLaPiedraFilosofal.jpg',price:'$12.000',},
  {id:13,name:'El Maravilloso Mago De Oz',src:'Images/ElMaravillosoMagoDeOz.jpg',price:'$12.000',},
  {id:14,name:'La Legión Perdida',src:'Images/LaLegiónPerdida.jpg',price:'$12.000',},
  {id:15,name:'Las Mil Y Una Noches',src:'Images/LasMilYUnaNoches.jpg',price:'$12.000',},
  {id:16,name:'Romeo Y Julieta',src:'Images/RomeoYJulieta.jpg',price:'$12.000',},
  {id:17,name:'HAMLET',src:'Images/HAMLET.jpg',price:'$12.000',},
  {id:18,name:'Guerra Y Paz',src:'Images/GuerraYPaz.jpg',price:'$12.000',},
  {id:19,name:'Harry Potter Y La Piedra Filosofal',src:'Images/HarryPotterYLaPiedraFilosofal.jpg',price:'$12.000',},
  {id:20,name:'Harry Potter Y La Piedra Filosofal',src:'Images/HarryPotterYLaPiedraFilosofal.jpg',price:'$12.000',},
  {id:20,name:'Harry Potter Y La Piedra Filosofal',src:'Images/HarryPotterYLaPiedraFilosofal.jpg',price:'$12.000',},
  {id:20,name:'Harry Potter Y La Piedra Filosofal',src:'Images/HarryPotterYLaPiedraFilosofal.jpg',price:'$12.000',},
  {id:20,name:'Harry Potter Y La Piedra Filosofal',src:'Images/HarryPotterYLaPiedraFilosofal.jpg',price:'$12.000',},
  {id:20,name:'Harry Potter Y La Piedra Filosofal',src:'Images/HarryPotterYLaPiedraFilosofal.jpg',price:'$12.000',},
];